defaults: &defaults
  adapter: mysql2
  username: root
  password: 
  host: localhost
  port: 3306
  encoding: utf8

development: 
  <<: *defaults
  database: library_to_go_development

test:
  <<: *defaults
  database: library_to_go_test
