defaults: &defaults
  adapter: postgresql
  username: postgresql
  password: 
  encoding: utf8

development: 
  <<: *defaults
  database: library_to_go_development

test:
  <<: *defaults
  database: library_to_go_test
  min_messages: WARNING

staging:
  <<: *defaults
  database: library_to_go_staging
  min_messages: WARNING
