defaults: &defaults
  morphology:
      - stem_en
  enable_star: true
  mem_limit: 32M
  max_matches: 1000
  html_strip: true
  min_infix_len: 3

development:
  <<: *defaults
test:
  <<: *defaults
  # workaround for slow indexing due to primary ID behavior of fixtures
  # http://freelancing-god.github.com/ts/en/common_issues.html#slow_indexing
  sql_range_step: 10000000
staging:
  <<: *defaults
production:
  <<: *defaults
